### PR TITLE
Add cooldown period

### PR DESCRIPTION
**Pull request by oppegard**
[#187613731](https://www.pivotaltracker.com/story/show/187613731)

### CODE REVIEW

**Comment by oppegard** [comment]
Hi @pspinrad, we have this ready to go for TAS 7.0. However, it's also being released in upcoming patch versions of TAS 6 and TAS 4. Since the feature isn't actually released to customers yet, is there any suggestion for whether this should be cherry-picked to other TAS branches, or how best to coordinate that (assuming the docs are published with regular cadence to docs.vmware.com)?

**Comment by pspinrad** [comment]
Thanks @oppegard -- just merged and SHA is 04e3cb656811350a3aaf1bfe0efa7b5ac879e758 -- I'll create Tracker stories to cherry-pick that merge commit into TAS 6 and TAS 4 patches when those come out.  Q's:
1. Will they be in the next patch versions, 6.0.6 and 4.0.26?
2. What about v5.0 -- are we leaving that version behind for this?

**Comment by oppegard** [comment]
Thanks @pspinrad. We're working to cut an autoscaler bosh release and verify that it's pulled into the `pivotal/tas` TAS 4, 5, and 6 branches. Once confirmed, we'll let you know so that you can update the Tracker stories on the specific patch versions that will include the new release.

**Comment by pspinrad** [comment]
@oppegard perfect, sound good-- story is here: https://www.pivotaltracker.com/story/show/187972829

**Comment by oppegard** [comment]
Hi @pspinrad, the new autoscaler release has been merged into the TAS 4, 5, and 6 branches. It'll be included in their next patch releases.

**Pull request merged**
