### PR TITLE
Update download urls for Broadcom

### PR DESCRIPTION
**Pull request by mkocher**
- Update urls to go to broadcom customer support portal. Unfortunately the link only redirects to a login page.
- Update one instance of Tanzu Network to vars.product_network

### CODE REVIEW

**Comment by mkocher** [comment]
Opening this against the main branch, please let us know if you would like us to open backport PRs as well.

**Comment by anita-flegg** [comment]
Thanks @mkocher. 
I am happy to cherry-pick this PR to all of the other releases.
Does this go back all the way to 2.11?

**Comment by mkocher** [comment]
Yes, the same URL should work back to 2.11

**Comment by anita-flegg** [comment]
Thanks, I was really wondering whether the plug-in was used that far back. I should be able to tell, though, by looking at the text.

**Comment by anita-flegg** [comment]
Done -- cherry-picked to 6.0, 5.0, 4.0, 2,13. 2.11

**Pull request merged**
