### PR TITLE
add output.html containing api documentation

### PR DESCRIPTION
**Pull request by hdub2**
Signed-off-by: Hunter Williams huwilliams@pivotal.io

### CODE REVIEW

**Comment by ljarzynski** [comment]
@hdub2 I noticed that some headings are duplicated (see attached image). Do you think we could re-generate? For instance, so that there's not another second level "service bindings" heading under service bindings?
screen shot 2016-10-28 at 11 13 44 am

**Comment by hdub2** [comment]
The reason there are some double headers is that there might be multiple
endpoints for a resource, i.e. Scheduled Limit Changes have a URI without a
guid parameter for the index and create, but require the parameter for
update and delete.  We'll take a look at it Monday morning, and maybe Scott
can help us compare with an existing example to see how they document it.

hw

On Fri, Oct 28, 2016 at 12:15 PM, Landon Jarzynski <notifications@github.com

**Comment by hdub2** [comment]
@ljarzynski Scott is going to compare these with the style that OpsMan is using and get with you.  I understand what you'd like to see, but not sure how to reconcile it within the constraints of the API Blueprint style.

**Comment by ljarzynski** [comment]
@hdub2 sounds good. I was also planning on talking to Ops Man about how they generate their API docs.

**Comment by slhommed** [comment]
I think this can be closed without merging.  We have the API docs covered via https://github.com/pivotal-cf/cf-autoscaling-release/tree/master/docs

**Comment by jncd** [comment]
Thanks @slhommed Closing this PR now.

**Pull request closed without merging**
